import React from "react";
import { CgWorkAlt } from "react-icons/cg";
import { LuGraduationCap } from "react-icons/lu";
import { IconType } from 'react-icons';
import { FaHome, FaLinkedin, FaBlog, FaInfoCircle, FaEnvelope, FaProjectDiagram,FaCode,  FaBook, FaFacebook, FaInstagram, FaGithub, FaYoutube, FaTwitter, FaMedium, FaSpotify } from 'react-icons/fa';

export interface FooterLink {
  href?: string;
  hash?: string;
  name: string;
  icon: IconType;
}


import { SectionName } from "@/context/active-section-context";
import spotify from "@/pages/api/spotify";

export const LINKS: { href?: string; hash?: string; name: SectionName }[] = [
  { href: "/", name: "Home" },
  { hash: "#about", name: "About" },
  { hash: "#skills", name: "Skills" },
  // { hash: "#experience", name: "Experience" },
  { href: "/posts", name: "Articles" },
  // { hash: "#contact", name: "Contact" },

];


export const EXPERIENCES_DATA = [
  
  {
    title: "Freelance Web Developer",
    location: "Kirsehir, Turkiye",
    description:
      "Using WordPress and WooCommerce, I've developed e-commerce apps for local businesses. These apps are easy to use and help businesses manage their online stores effectively.",
      icon: React.createElement(CgWorkAlt),
      date: "April   2020 - June 2022",
  },
  {
    title: "Ahi Evran University Computer Science GPA: 3.05 ",
    location: "Kirsehir, Turkiye",
    description:
    "During my university education, I focused on web applications and AI. I took several courses that provided a deep understanding of these subjects. I gained hands-on experience in developing and working with web applications and explored various AI tech", 
    icon: React.createElement(LuGraduationCap),
    date: "May - 2024",

  },
  {
    title: "C ve Sistem Programlama Dernegi",
    location: "Istanbul, Turkiye",
    description:      
      "The course covers microcontroller fundamentals, focusing on general and ARM microcontroller principles, software development without an operating system, basic software architectures, multitasking, and common communication protocols. Projects will be developed using C programming language and low-level system and hardware libraries. It aims to provide both introductory and advanced knowledge on microcontroller applications, with additional basic electronics and measurement tool usage.",
    icon: React.createElement(CgWorkAlt),
    date: "July 2024 - present",

  },
  {
    title: "Intern",
    location: "Istanbul, Turkiye",
    description:
      "",
    icon: React.createElement(CgWorkAlt),
    date: "",

  },
] as const;




// Data for skills
export const SKILLS1_DATA = [
 ,
  "ARM Assembly",
  "ARM® Cortex® -M3 & M4 MCU Architecture",
  "Embedded Driver Development",

  "STM32",
  "ESP32",
  "GPIO",
  "Interputs",
  "Timers",
  "ADC/DAC",
  "PWM",
  "DMA",
  "UART",
  "USART",
  "SPI",
  "I²C",
  "1-Wire Bus Protocol",
  "CANBUS",
  "MODBUS",
  "CMake",
  "TDD",
  "Unit Testing"
] as const;

// Data for skills
export const SKILLS2_DATA = [ 
  "C",
  "Python",
] as const;


// Data for skills
export const SKILLS3_DATA = [ 
// "QT Framework",
// "Three.js",
// "WebGL",
// "Blender",
] as const;

// Data for skills
export const SKILLS4_DATA = [ 
  "HTML",
  "CSS",
  "Tailwind CSS",
  "JavaScript",
  "TypeScript",
  "React.js",
  "Next.js",
  "WordPress",
  "WooCommerce",
  "/",
  "Numpy",
  "Pandas",
  "Matplotlib",
  "Seaborn",
  "Scikit-Learn",
  "PyTorch",
  "OpenAI API",
  "Llama 3",
  "Mixtral 8x7B"
] as const;


// Data for skills
export const SKILLS5_DATA = [ 
  "Git",
  "VSCode",
  "Vim",
  "STM32CubeIDE",
  "Atollic TrueSTUDIO",
  "IAR Embedded Workbench for ARM",
] as const;

// Data for skills
export const SKILLS6_DATA = [    
  "Electronics",
  "Soldering",
  // "Basic PCB Design",
  // "Fusion 360", 
  "GNU Linux",
  "Network",
] as const;


// /constants/articlesData.ts
export const ARTICLES_DATA = [
  {
    date: "August 22, 2023",
    title: "Lighting Control",
    description: "The system will control home lighting using PWM signals generated by the STM32.",
    keywords: ["STM32", "PWM", "UART", "Lighting Control"],
    slug: "md-1",
    number: 1, 
    image: "../postDataImg19.png",
    category: "Embedded Software",
    subcategory: "STM32 Microcontroller",
    type: "project",

  },
  {
    date: "2023-03-22",
    title: "Temperature and Humidity Monitoring",
    description: "The system will control home lighting using PWM signals generated by the STM32.",
    keywords: ["STM32", "I2C", "Temperature Sensor", "Humidity Sensor"],
    slug: "md-2",
    number: 2,
    image:  "../postDataImg16.png",
    category: "Embedded Software",
    subcategory: "Microcontrollers",
    type: "project",



  },
  {
    date: "2023-03-22",
    title: "Security System",
    description: "The system will control home lighting using PWM signals generated by the STM32.",
    keywords: ["STM32", "PIR Sensor", "SPI", "Wi-Fi Module"],
    slug: "md-3",
    number: 3,
    image:  "../postDataImg17.png",
    category: "Web Development",
    subcategory: "General",
    type: "project",

  },
  {
    date: "2023-03-22",
    title: "Real-Time Clock (RTC)",
    description: "The system will control home lighting using PWM signals generated by the STM32.",
    keywords: ["STM32", "RTC", "Timekeeping", "Automation"],
    slug: "md-4",
    number: 4,
    image:  "../postDataImg14.png",
    category: "Programming",
    subcategory: "General",
    type: "project",

  },
  {
    date: "2013-03-22",
    title: "Remote Monitoring and Control",
    description: "The system will control home lighting using PWM signals generated by the STM32.",
    keywords: ["STM32", "Wi-Fi", "Remote Control", "Mobile App"],
    slug: "md-5",
    number: 5,
    image:  "../postDataImg8.png",
    category: "AI",
    subcategory: "General",
    type: "project",

  },

  {
    date: "2025-03-22",
    title: "Implementing SPI Communication on STM32",
    description: "Exploring the methodologies and technologies involved in creating robust intrusion detection systems for vehicle cybersecurity.",
    keywords: ["STM32", "SPI", "Communication", "Vehicle Security"],
    slug: "md-6",
    number: 6,
    image: "../postDataImg7.png",
    category: "Embedded Software",
    subcategory: "General",
    type: "project",

  },
  {
    date: "2026-03-22",
    title: "Real-Time Clock (RTC) Configuration on STM32",
    description: "Exploring the methodologies and technologies involved in creating robust intrusion detection systems for vehicle cybersecurity.",
    keywords: ["STM32", "RTC", "Configuration", "Timekeeping"],
    slug: "md-7",
    number: 7,
    image: "../postDataImg6.png",  
    category: "Embedded Software",
    subcategory: "General",
    type: "project",

  }, 
  {
    date: "2023-03-22",
    title: "Real-Time Clock (RTC) Configuration on STM32",
    description: "Exploring the methodologies and technologies involved in creating robust intrusion detection systems for vehicle cybersecurity.",
    keywords: ["STM32", "RTC", "Configuration", "Timekeeping", "RTOS"],
    slug: "md-8",
    number: 8,
    image: "../postDataImg12.png",
    category: "Embedded Software",
    subcategory: "General",
    type: "project",

  }, 
  {
    date: "2023-05-22",
    title: "Real-Time Clock (RTC) Configuration on STM32",
    description: "Exploring the methodologies and technologies involved in creating robust intrusion detection systems for vehicle cybersecurity.",
    keywords: ["STM32", "RTC", "Configuration", "Timekeeping"],
    slug: "md-9",
    number: 9,
    image: "../postDataImg11.png",  
    category: "Embedded Software",
    subcategory: "General",
    type: "project",

  }, 

  {
    date: "2023-06-11",
    title: "Real-Time Clock (RTC) Configuration on STM32",
    description: "Exploring the methodologies and technologies involved in creating robust intrusion detection systems for vehicle cybersecurity.",
    keywords: ["STM32", "RTC", "Configuration", "Timekeeping"],
    slug: "md-10",
    number: 10,
    image: "../postDataImg15.png",  
    category: "Embedded Software",
    subcategory: "General",
    type: "project",

  }, 
];

// Owner name
export const OWNER_NAME = "Emre KALAYCİ";


export const FOOTER_LINKS: FooterLink[] = [
  { hash: "#home", name: "Home", icon: FaHome },
  { hash: "#about", name: "About", icon: FaInfoCircle },
  { hash: "#skills", name: "Skills", icon: FaProjectDiagram },
  { hash: "#articles", name: "Articles", icon: FaBook },
  { hash: "#contact", name: "Contact", icon: FaEnvelope },
];

 export const EXTRA_LINKS: { [key: string]: { href: string; icon: IconType } } = {  
   linkedin: { href: "https://www.linkedin.com/in/emre-kalayc%C4%B1-b22a651bb/", icon: FaLinkedin },
   resume: {href: "./resume.pdf", icon: FaProjectDiagram},
  github: { href: "https://github.com/ek-uint61", icon: FaGithub },
  facebook: { href: "https://www.facebook.com", icon: FaFacebook },
  instagram: { href: "https://www.instagram.com", icon: FaInstagram },
   twitter: { href: "https://X.com", icon: FaTwitter },
   source: {href: "https://github.com/ek-uint61/personal_portfolio_blog", icon: FaCode },
   medium: {href: "", icon: FaMedium },
   spotify: {href: "", icon: FaSpotify },
 } as const;

 export const OTHER_LINKS = {
  linkedin: "https://www.linkedin.com/in/emre-kalayc%C4%B1-b22a651bb/",
  github: "https://github.com/ek-uint61",
  resume: "/resume.pdf",
} as const;

